### ISSUE TITLE
Плагин не имеет настроек ?

### ISSUE THREAD

**Issue by Baltazar500** [krlvm/PowerTunnel-AdBlock#1]
Плагин не имеет настроек ? А как им пользоваться ?

**Comment by krlvm** [comment]
На данный момент плагин подгружает список Adware & Malware [отсюда](https://github.com/StevenBlack/hosts) и блокирует эти хосты. В текущей версии есть некоторые недостатки, а еще после применения этого списка почему-то отваливается YouTube, поэтому я временно исключил плагин из стандартной поставки. В следующей версии он будет работать быстрее благодаря новому API фильтрации DNS (в текущей версии трафик фильтруется напрямую), а также будет опция для добавления кастомных списков. По сути этот плагин дублирует функциональность двух готовящихся плагинов - Hosts и Filter.

**Comment by krlvm** [comment]
P.S.: Эти тесты показывают достаточно высокую эффективность с учетом того, что блокировка рекламы осуществляется по хостам без инъекции скрипта блокировщика рекламы напрямую в веб-страницы: [1](https://d3ward.github.io/toolz/adblock), [2](https://checkadblock.ru/).

**Comment by krlvm** [comment]
В версии 1.0-rc2 можно указать способ фильтрации (DNS более производительный), эта версия поставляется с приложением для Android версии 2.0-rc4.
